# Site settings
title: laohugou
email: qwfys200@qq.com
description: We thrive on the road together
baseurl: "/laohugou"
url: "http://nandomoreira.me"

author:
  name     : 'lwk'
  email    : qwfys200@qq.com
  url      : https://github.com/qwfys
  facebook : http://facebook.com/qwfys200
  twitter  : https://twitter.com/qwfys200

github: https://github.com/qwfys/laohugou
disqus_shortname: "qwfys200"
google_analytics: G-L1DG75H9NF

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
